/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: process + database. Cold Neon wakes are tolerated by db.ping() (one retry) and
         *     the generous `db_health_timeout`. Never 500 — return `db:'down'` so the frontend can decide.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Kick off a crawl. Returns 202 immediately; the pipeline runs in a background task.
         *
         *     Single intake row per trigger — `run_crawl` reuses this id so `/crawl/runs` doesn't get
         *     two rows (one "wrapper", one "real") like the earlier version produced.
         */
        post: operations["start_run_crawl_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show Run */
        get: operations["show_run_crawl_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_crawl_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Run */
        get: operations["latest_run_crawl_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Leads */
        get: operations["list_leads_leads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show Lead */
        get: operations["show_lead_leads__lead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Email */
        post: operations["draft_email_email_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        /** Put Settings */
        put: operations["put_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capacity/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_capacity_posts_get"];
        put?: never;
        /** Create Post */
        post: operations["create_post_capacity_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capacity/posts/{post_id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggestions */
        get: operations["suggestions_capacity_posts__post_id__suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/call-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Call List */
        get: operations["get_call_list_tools_call_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/call-list/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Outcome */
        post: operations["log_outcome_tools_call_list_outcome_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/call-list/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_tools_call_list_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/shipper-finder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shippers */
        get: operations["list_shippers_tools_shipper_finder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/shipper-finder/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Promote */
        post: operations["promote_tools_shipper_finder_promote_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/shipper-finder/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shipper */
        get: operations["get_shipper_tools_shipper_finder__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrichment/leads/{lead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lead Enrichment */
        get: operations["get_lead_enrichment_enrichment_leads__lead_id__get"];
        put?: never;
        /** Enrich Lead Route */
        post: operations["enrich_lead_route_enrichment_leads__lead_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrichment/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enrich Candidate Route */
        post: operations["enrich_candidate_route_enrichment_candidates__candidate_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrichment/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_enrichment_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrichment/auto-send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto Send
         * @description Route-level auth (BLOCKING-2 fix). Application-level `auto_outreach_enabled`
         *     is a *what*, not a *who* — this guard makes sure only the cron caller can ask.
         */
        post: operations["auto_send_enrichment_auto_send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unsubscribe Confirm Page
         * @description GET renders a confirm page — NEVER mutates.
         *
         *     Email security scanners (Microsoft Safe Links, Google, Proofpoint) auto-fetch
         *     every URL in every outbound email. If GET mutated, one scanned inbox would
         *     unsubscribe the recipient before they read the message. Confirm-then-POST is
         *     the CAN-SPAM one-click contract (RFC 8058); we honor it.
         */
        get: operations["unsubscribe_confirm_page_unsubscribe_get"];
        put?: never;
        /**
         * Unsubscribe Post
         * @description POST performs the suppression. Same route also accepts RFC 8058
         *     `List-Unsubscribe=One-Click` payloads via `?t=<token>` on the query string.
         *     Invalid / forged token → 400 with zero side effects.
         */
        post: operations["unsubscribe_post_unsubscribe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutoSendIn */
        AutoSendIn: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /** Now Hour Override */
            now_hour_override?: number | null;
        };
        /** AutoSendOut */
        AutoSendOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "disabled" | "no_footer" | "no_template" | "no_unsub_config" | "outside_window";
            /** Sent */
            sent: number;
            /** Skipped Suppressed */
            skipped_suppressed: number;
            /** Skipped Cap */
            skipped_cap: number;
            /** Dry Run */
            dry_run: boolean;
        };
        /** CallListOut */
        CallListOut: {
            /** Date */
            date: string;
            /** Items */
            items: components["schemas"]["CallRowOut"][];
        };
        /** CallRowOut */
        CallRowOut: {
            /** Lead Id */
            lead_id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** City */
            city: string | null;
            /** Phone */
            phone: string;
            /** Primary Email */
            primary_email: string | null;
            /** Score */
            score: number;
            /** Reasons */
            reasons: string[];
            /** Opener */
            opener: string;
            last_outcome: components["schemas"]["LastOutcomeOut"] | null;
        };
        /** CrawlRunOut */
        CrawlRunOut: {
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Kind */
            kind: string;
            /** Trigger */
            trigger: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Counts */
            counts: {
                [key: string]: unknown;
            };
            /** Error */
            error?: string | null;
        };
        /** DecisionMakerOut */
        DecisionMakerOut: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Title */
            title: string | null;
            /** Linkedin Url */
            linkedin_url: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Confidence */
            confidence: string | null;
            /** Source */
            source: string | null;
            /** Source Url */
            source_url: string | null;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            } | null;
            /** Last Verified At */
            last_verified_at: string | null;
            /** Pipeline Status */
            pipeline_status: string;
        };
        /** DraftIn */
        DraftIn: {
            /** Lead Id */
            lead_id?: string | null;
            /** Lead */
            lead?: {
                [key: string]: unknown;
            } | null;
            /**
             * Tone
             * @default professional
             * @enum {string}
             */
            tone: "professional" | "friendly" | "direct" | "persuasive";
            /** Instructions */
            instructions?: string | null;
        };
        /** DraftOut */
        DraftOut: {
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Body Html */
            body_html: string;
            /**
             * Source
             * @enum {string}
             */
            source: "gemini" | "fallback";
            /**
             * Tone
             * @enum {string}
             */
            tone: "professional" | "friendly" | "direct" | "persuasive";
            /** Lead Id */
            lead_id?: string | null;
            /** Stance */
            stance?: ("positive" | "neutral" | "cooling") | null;
        };
        /** EnrichmentMetricsOut */
        EnrichmentMetricsOut: {
            /**
             * Scope
             * @enum {string}
             */
            scope: "shipper" | "broker";
            /** Window Days */
            window_days: number;
            /** Enriched */
            enriched: number;
            /** Reachable */
            reachable: number;
            /** Contacted */
            contacted: number;
            /** Replied */
            replied: number;
            /** Enriched All Time */
            enriched_all_time: number;
            /** Reachable All Time */
            reachable_all_time: number;
            /** Reachable Rate */
            reachable_rate: number;
            /** Replied Rate */
            replied_rate: number;
        };
        /** EnrichmentResultOut */
        EnrichmentResultOut: {
            /** Lead Id */
            lead_id: string | null;
            /** Candidate Id */
            candidate_id: string | null;
            /** Status */
            status: string;
            /** Error */
            error: string | null;
            /** Is Js Only Site */
            is_js_only_site: boolean;
            /** Decision Makers */
            decision_makers: components["schemas"]["DecisionMakerOut"][];
            /** Contacts */
            contacts: components["schemas"]["WebsiteContactOut"][];
            /** Pages Fetched */
            pages_fetched: number;
            /** Linkedin Company Url */
            linkedin_company_url: string | null;
            /** Website Url */
            website_url: string | null;
            /** Ran At */
            ran_at: string;
            /** Per Stage */
            per_stage?: {
                [key: string]: string;
            };
            /** Fit Score */
            fit_score?: number | null;
            /** Fit Reasons */
            fit_reasons?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /**
             * Db
             * @enum {string}
             */
            db: "up" | "down";
            /** App Env */
            app_env: string;
        };
        /** LastOutcomeOut */
        LastOutcomeOut: {
            /** Outcome */
            outcome: string;
            /** Logged At */
            logged_at: string | null;
        };
        /** LeadDetail */
        LeadDetail: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** City */
            city?: string | null;
            /** Mc */
            mc?: string | null;
            /** Dot */
            dot?: string | null;
            /** Domain */
            domain?: string | null;
            /** Primary Email */
            primary_email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Current Score */
            current_score?: number | null;
            /** First Seen At */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at: string;
            /**
             * Sources
             * @default []
             */
            sources: string[];
            /** Address */
            address?: string | null;
            /**
             * Raw
             * @default {}
             */
            raw: {
                [key: string]: unknown;
            };
            /**
             * Evidence
             * @default {}
             */
            evidence: {
                [key: string]: unknown;
            };
            /**
             * Contacts
             * @default []
             */
            contacts: {
                [key: string]: unknown;
            }[];
            /** Score */
            score?: {
                [key: string]: unknown;
            } | null;
        };
        /** LeadOut */
        LeadOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** City */
            city?: string | null;
            /** Mc */
            mc?: string | null;
            /** Dot */
            dot?: string | null;
            /** Domain */
            domain?: string | null;
            /** Primary Email */
            primary_email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Current Score */
            current_score?: number | null;
            /** First Seen At */
            first_seen_at: string;
            /** Last Seen At */
            last_seen_at: string;
            /**
             * Sources
             * @default []
             */
            sources: string[];
        };
        /** LeadsPage */
        LeadsPage: {
            /** Items */
            items: components["schemas"]["LeadOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** OutcomeHistoryOut */
        OutcomeHistoryOut: {
            /** Lead Id */
            lead_id: string;
            /** Items */
            items: components["schemas"]["OutcomeHistoryRow"][];
        };
        /** OutcomeHistoryRow */
        OutcomeHistoryRow: {
            /** Id */
            id: number;
            /** Outcome */
            outcome: string;
            /** Callback At */
            callback_at: string | null;
            /** Note */
            note: string | null;
            /** Logged At */
            logged_at: string;
            /** Logged By */
            logged_by: string | null;
        };
        /** OutcomeIn */
        OutcomeIn: {
            /** Lead Id */
            lead_id: string;
            /** Outcome */
            outcome: string;
            /** Callback At */
            callback_at?: string | null;
            /** Note */
            note?: string | null;
        };
        /** PostIn */
        PostIn: {
            /** Kind */
            kind: string;
            /** Equipment */
            equipment: string;
            /** Origin City */
            origin_city?: string | null;
            /** Origin State */
            origin_state: string;
            /**
             * Destinations
             * @default []
             */
            destinations: string[];
            /** Available Date */
            available_date?: string | null;
            /** Dest City */
            dest_city?: string | null;
            /** Dest State */
            dest_state?: string | null;
            /** Pickup Date */
            pickup_date?: string | null;
            /** Weight Lbs */
            weight_lbs?: number | null;
            /** Rate Usd */
            rate_usd?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** PostList */
        PostList: {
            /** Items */
            items: components["schemas"]["PostOut"][];
        };
        /** PostOut */
        PostOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Equipment */
            equipment: string;
            /** Origin City */
            origin_city: string | null;
            /** Origin State */
            origin_state: string;
            /** Destinations */
            destinations: string[];
            /** Available Date */
            available_date: string | null;
            /** Dest City */
            dest_city: string | null;
            /** Dest State */
            dest_state: string | null;
            /** Pickup Date */
            pickup_date: string | null;
            /** Weight Lbs */
            weight_lbs: number | null;
            /** Rate Usd */
            rate_usd: number | null;
            /** Notes */
            notes: string | null;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** PromoteIn */
        PromoteIn: {
            /** Candidate Id */
            candidate_id: string;
        };
        /** PromoteOut */
        PromoteOut: {
            /** Lead Id */
            lead_id: string;
            /** Created */
            created: boolean;
        };
        /** PromotedLeadOut */
        PromotedLeadOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** City */
            city: string | null;
            /** Kind */
            kind: string;
            /** Mc */
            mc: string | null;
            /** Dot */
            dot: string | null;
            /** Domain */
            domain: string | null;
            /** Phone */
            phone: string | null;
            /** Primary Email */
            primary_email: string | null;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Threshold */
            threshold: number;
            /** Auto Send Enabled */
            auto_send_enabled: boolean;
            /** Auto Send Template Id */
            auto_send_template_id: string | null;
            /** Tone */
            tone: string;
            /** Daily Send Cap */
            daily_send_cap: number;
            /** Updated At */
            updated_at: string;
            /** Auto Outreach Enabled */
            auto_outreach_enabled: boolean;
            /** Auto Outreach Template Id */
            auto_outreach_template_id: string | null;
            /** Auto Outreach Daily Cap */
            auto_outreach_daily_cap: number;
            /** Auto Outreach Window Start H */
            auto_outreach_window_start_h: number;
            /** Auto Outreach Window End H */
            auto_outreach_window_end_h: number;
            /** Auto Outreach Status Filter */
            auto_outreach_status_filter: string;
            /** Auto Outreach Min Fit */
            auto_outreach_min_fit: number;
            /** Fit Weights */
            fit_weights: {
                [key: string]: unknown;
            } | null;
            /** Unsubscribe Base Url */
            unsubscribe_base_url: string | null;
            /** Unsub Secret Set */
            unsub_secret_set: boolean;
            /** Unsub Config Ready */
            unsub_config_ready: boolean;
        };
        /** SettingsPatch */
        SettingsPatch: {
            /** Threshold */
            threshold?: number | null;
            /** Auto Send Enabled */
            auto_send_enabled?: boolean | null;
            /** Auto Send Template Id */
            auto_send_template_id?: string | null;
            /** Tone */
            tone?: string | null;
            /** Daily Send Cap */
            daily_send_cap?: number | null;
            /** Auto Outreach Enabled */
            auto_outreach_enabled?: boolean | null;
            /** Auto Outreach Template Id */
            auto_outreach_template_id?: string | null;
            /** Auto Outreach Daily Cap */
            auto_outreach_daily_cap?: number | null;
            /** Auto Outreach Window Start H */
            auto_outreach_window_start_h?: number | null;
            /** Auto Outreach Window End H */
            auto_outreach_window_end_h?: number | null;
            /** Auto Outreach Status Filter */
            auto_outreach_status_filter?: string | null;
            /** Auto Outreach Min Fit */
            auto_outreach_min_fit?: number | null;
            /** Fit Weights */
            fit_weights?: {
                [key: string]: unknown;
            } | null;
            /** Unsubscribe Base Url */
            unsubscribe_base_url?: string | null;
        };
        /** ShipperDetailOut */
        ShipperDetailOut: {
            row: components["schemas"]["ShipperRowOut"];
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            } | null;
            /** Osm Tags */
            osm_tags: {
                [key: string]: unknown;
            } | null;
            /** Raw */
            raw: {
                [key: string]: unknown;
            } | null;
            /** Osm Ref */
            osm_ref: string | null;
            /** Fmcsa Mc */
            fmcsa_mc: string | null;
            /** Fmcsa Dot */
            fmcsa_dot: string | null;
            /** First Seen At */
            first_seen_at: string | null;
            /** Last Seen At */
            last_seen_at: string | null;
            promoted_lead: components["schemas"]["PromotedLeadOut"] | null;
        };
        /** ShipperListOut */
        ShipperListOut: {
            /** Items */
            items: components["schemas"]["ShipperRowOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ShipperRowOut */
        ShipperRowOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** City */
            city: string | null;
            /** Address */
            address: string | null;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
            /** Sources */
            sources: string[];
            /** Mc */
            mc: string | null;
            /** Dot */
            dot: string | null;
            /** Domain */
            domain: string | null;
            /** Phone */
            phone: string | null;
            /** Primary Email */
            primary_email: string | null;
            /** Score */
            score: number;
            /** Reasons */
            reasons: string[];
            /** Promoted Lead Id */
            promoted_lead_id: string | null;
            /** Match Reason */
            match_reason: string | null;
            /** Fit Score */
            fit_score?: number | null;
            /** Fit Reasons */
            fit_reasons?: string[];
        };
        /** SuggestionList */
        SuggestionList: {
            post: components["schemas"]["PostOut"];
            /** Items */
            items: components["schemas"]["SuggestionOut"][];
        };
        /** SuggestionOut */
        SuggestionOut: {
            /** Lead Id */
            lead_id: string;
            /** Name */
            name: string;
            /** State */
            state: string;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Score */
            score: number;
            /** Reason */
            reason: string;
        };
        /** UnsubscribeOut */
        UnsubscribeOut: {
            /** Ok */
            ok: boolean;
            /** Email */
            email: string | null;
            /** Already */
            already: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebsiteContactOut */
        WebsiteContactOut: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Title */
            title: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Confidence */
            confidence: string | null;
            /** Source */
            source: string | null;
            /** Source Url */
            source_url: string | null;
            /** Last Verified At */
            last_verified_at: string | null;
            /** Pipeline Status */
            pipeline_status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    start_run_crawl_run_post: {
        parameters: {
            query?: {
                trigger?: string;
                limit?: number;
            };
            header?: {
                "X-Cron-Secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_run_crawl_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_crawl_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_run_crawl_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrawlRunOut"] | null;
                };
            };
        };
    };
    list_leads_leads_get: {
        parameters: {
            query?: {
                state?: string | null;
                kind?: string | null;
                min_score?: number | null;
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadsPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    show_lead_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_email_email_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    put_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_capacity_posts_get: {
        parameters: {
            query?: {
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_capacity_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestions_capacity_posts__post_id__suggestions_get: {
        parameters: {
            query?: {
                top?: number;
            };
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_call_list_tools_call_list_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_outcome_tools_call_list_outcome_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_tools_call_list_history_get: {
        parameters: {
            query: {
                lead_id: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutcomeHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shippers_tools_shipper_finder_get: {
        parameters: {
            query?: {
                state?: string | null;
                source?: ("FMCSA" | "OSM" | "Gemini" | "Both") | null;
                min_score?: number | null;
                promoted?: boolean | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
                sort?: "lane" | "fit";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipperListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    promote_tools_shipper_finder_promote_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shipper_tools_shipper_finder__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipperDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lead_enrichment_enrichment_leads__lead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_lead_route_enrichment_leads__lead_id__post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                lead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_candidate_route_enrichment_candidates__candidate_id__post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_enrichment_metrics_get: {
        parameters: {
            query?: {
                kind?: "shipper" | "broker";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentMetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_send_enrichment_auto_send_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Cron-Secret"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoSendIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoSendOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_confirm_page_unsubscribe_get: {
        parameters: {
            query: {
                t: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_post_unsubscribe_post: {
        parameters: {
            query: {
                t: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnsubscribeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
